### ISSUE TITLE
Ошибка в алгоритме к-средних

### ISSUE THREAD

**Issue by LasTAD** [LasTAD/memorand#9]
Traceback (most recent call last):
  File "/Users/nikolaikobyzev/Documents/Для учебы/Курсовые проекты/ТРСПО/memorand/memorand/memgen.py", line 33, in <module>
    main()
  File "/Users/nikolaikobyzev/Documents/Для учебы/Курсовые проекты/ТРСПО/memorand/memorand/memgen.py", line 21, in main
    meme = mg.create_meme()
  File "/Users/nikolaikobyzev/Documents/Для учебы/Курсовые проекты/ТРСПО/memorand/memorand/MemeMan.py", line 102, in create_meme
    img = put_text_pil(img, db.get_phrase())
  File "/Users/nikolaikobyzev/Documents/Для учебы/Курсовые проекты/ТРСПО/memorand/memorand/MemeMan.py", line 82, in put_text_pil
    font_col = k_mean.pick_color(img, text_size)
  File "/Users/nikolaikobyzev/Documents/Для учебы/Курсовые проекты/ТРСПО/memorand/memorand/k_mean.py", line 82, in pick_color
    col = colorz(img)
  File "/Users/nikolaikobyzev/Documents/Для учебы/Курсовые проекты/ТРСПО/memorand/memorand/k_mean.py", line 29, in colorz
    clusters = kmeans(points, n, 1)
  File "/Users/nikolaikobyzev/Documents/Для учебы/Курсовые проекты/ТРСПО/memorand/memorand/k_mean.py", line 59, in kmeans
    distance = euclidean(p, clusters[i].center)
  File "/Users/nikolaikobyzev/Documents/Для учебы/Курсовые проекты/ТРСПО/memorand/memorand/k_mean.py", line 36, in euclidean
    (p1.coords[i] - p2.coords[i]) ** 2 for i in range(p1.n)
  File "/Users/nikolaikobyzev/Documents/Для учебы/Курсовые проекты/ТРСПО/memorand/memorand/k_mean.py", line 36, in <listcomp>
    (p1.coords[i] - p2.coords[i]) ** 2 for i in range(p1.n)
TypeError: 'int' object is not subscriptable

**Comment by LasTAD** [comment]
Модуль к-средних отключен
